"""initial_schema

Revision ID: 46134265e0d7
Revises: 
Create Date: 2026-02-08 21:39:49.539427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46134265e0d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL OR researcher_id IS NOT NULL'),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.researchers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token'),
    schema='users'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('responses', schema='scales')
    op.drop_table('drafts', schema='scales')
    op.drop_index(op.f('ix_researchers_username'), table_name='researchers', schema='users')
    op.create_index(op.f('ix_users_researchers_username'), 'researchers', ['username'], unique=True, schema='users')
    op.drop_index(op.f('ix_users_patient_number'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_patient_token'), table_name='users', schema='users')
    op.drop_constraint(op.f('users_patient_number_key'), 'users', schema='users', type_='unique')
    op.create_index(op.f('ix_users_users_patient_number'), 'users', ['patient_number'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_patient_token'), 'users', ['patient_token'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_patient_token'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_patient_number'), table_name='users', schema='users')
    op.create_unique_constraint(op.f('users_patient_number_key'), 'users', ['patient_number'], schema='users')
    op.create_index(op.f('ix_users_patient_token'), 'users', ['patient_token'], unique=True, schema='users')
    op.create_index(op.f('ix_users_patient_number'), 'users', ['patient_number'], unique=True, schema='users')
    op.drop_index(op.f('ix_users_researchers_username'), table_name='researchers', schema='users')
    op.create_index(op.f('ix_researchers_username'), 'researchers', ['username'], unique=True, schema='users')
    op.create_table('drafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('drafts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drafts_pkey')),
    schema='scales'
    )
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('raw_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interpretation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('responses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('responses_pkey')),
    schema='scales'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('sessions', schema='users')
    # ### end Alembic commands ###
