"""Initial schema creation from SQLAlchemy models.

Revision ID: 5e1f8a2c3b4d
Revises: 
Create Date: 2026-02-08 22:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e1f8a2c3b4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('gender', sa.String(), nullable=True),
        sa.Column('consent_personal_data', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('consent_bot_use', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('external_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('patient_token', sa.String(length=64), nullable=True),
        sa.Column('patient_number', sa.Integer(), nullable=True),
        sa.Column('pin_hash', sa.String(length=128), nullable=True),
        sa.Column('pin_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('patient_number'),
        sa.UniqueConstraint('patient_token'),
        sa.UniqueConstraint('telegram_id'),
        schema='users'
    )
    op.create_index(op.f('ix_users_users_patient_number'), 'users', ['patient_number'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_patient_token'), 'users', ['patient_token'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_telegram_id'), 'users', ['telegram_id'], unique=True, schema='users')
    op.create_table(
        'researchers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
        schema='users'
    )
    op.create_index(op.f('ix_users_researchers_username'), 'researchers', ['username'], unique=True, schema='users')
    op.create_table(
        'sessions',
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('researcher_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.CheckConstraint('user_id IS NOT NULL OR researcher_id IS NOT NULL'),
        sa.ForeignKeyConstraint(['researcher_id'], ['users.researchers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('token'),
        schema='users'
    )
    op.create_table(
        'scale_results',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('scale_code', sa.String(length=32), nullable=False),
        sa.Column('scale_version', sa.String(length=16), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('answers_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='scales'
    )
    op.create_index(op.f('ix_scale_results_measured_at'), 'scale_results', ['measured_at'], schema='scales')
    op.create_index(op.f('ix_scale_results_scale_code'), 'scale_results', ['scale_code'], schema='scales')
    op.create_index(op.f('ix_scale_results_user_id'), 'scale_results', ['user_id'], schema='scales')
    op.create_table(
        'bp_measurements',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('systolic', sa.Integer(), nullable=False),
        sa.Column('diastolic', sa.Integer(), nullable=False),
        sa.Column('pulse', sa.Integer(), nullable=True),
        sa.Column('context', sa.String(length=32), nullable=False, server_default='na'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='vitals'
    )
    op.create_index(op.f('ix_bp_measurements_measured_at'), 'bp_measurements', ['measured_at'], schema='vitals')
    op.create_index(op.f('ix_bp_measurements_session_id'), 'bp_measurements', ['session_id'], schema='vitals')
    op.create_table(
        'pulse_measurements',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('bpm', sa.Integer(), nullable=False),
        sa.Column('context', sa.String(length=32), nullable=False, server_default='na'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='vitals'
    )
    op.create_index(op.f('ix_pulse_measurements_measured_at'), 'pulse_measurements', ['measured_at'], schema='vitals')
    op.create_index(op.f('ix_pulse_measurements_session_id'), 'pulse_measurements', ['session_id'], schema='vitals')
    op.create_table(
        'weight_measurements',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column('context', sa.String(length=32), nullable=False, server_default='na'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='vitals'
    )
    op.create_index(op.f('ix_weight_measurements_measured_at'), 'weight_measurements', ['measured_at'], schema='vitals')
    op.create_index(op.f('ix_weight_measurements_session_id'), 'weight_measurements', ['session_id'], schema='vitals')
    op.create_table(
        'water_intake',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('volume_ml', sa.Integer(), nullable=False),
        sa.Column('liquid_type', sa.String(length=32), nullable=True),
        sa.Column('context', sa.String(length=32), nullable=False, server_default='na'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id']),
        sa.PrimaryKeyConstraint('id'),
        schema='vitals'
    )
    op.create_index(op.f('ix_water_intake_measured_at'), 'water_intake', ['measured_at'], schema='vitals')
    op.create_index(op.f('ix_water_intake_session_id'), 'water_intake', ['session_id'], schema='vitals')
    op.create_table(
        'lessons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=False),
        sa.Column('topic', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('short_description', sa.String(length=500), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lessons_code'), 'lessons', ['code'], unique=True, schema='education')
    op.create_index(op.f('ix_education_lessons_topic'), 'lessons', ['topic'], schema='education')
    op.create_table(
        'lesson_cards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('card_type', sa.String(length=30), nullable=False, server_default='text'),
        sa.Column('content_md', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lesson_cards_lesson_id'), 'lesson_cards', ['lesson_id'], schema='education')
    op.create_table(
        'practices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description_md', sa.Text(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_practices_lesson_id'), 'practices', ['lesson_id'], schema='education')
    op.create_table(
        'lesson_tests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('short_description', sa.String(length=512), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lesson_tests_code'), 'lesson_tests', ['code'], unique=True, schema='education')
    op.create_index(op.f('ix_education_lesson_tests_lesson_id'), 'lesson_tests', ['lesson_id'], schema='education')
    op.create_table(
        'lesson_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_token', sa.String(length=64), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('last_card_index', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('is_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], schema='education')
    op.create_index(op.f('ix_education_lesson_progress_patient_token'), 'lesson_progress', ['patient_token'], schema='education')
    op.create_table(
        'lesson_test_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('option_1', sa.Text(), nullable=False),
        sa.Column('option_2', sa.Text(), nullable=False),
        sa.Column('option_3', sa.Text(), nullable=False),
        sa.Column('option_4', sa.Text(), nullable=False),
        sa.Column('correct_option', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.ForeignKeyConstraint(['test_id'], ['education.lesson_tests.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lesson_test_questions_test_id'), 'lesson_test_questions', ['test_id'], schema='education')
    op.create_table(
        'practice_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('practice_id', sa.Integer(), nullable=False),
        sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('success', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('effect_rating', sa.Integer(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['practice_id'], ['education.practices.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_practice_logs_practice_id'), 'practice_logs', ['practice_id'], schema='education')
    op.create_index(op.f('ix_education_practice_logs_user_id'), 'practice_logs', ['user_id'], schema='education')
    op.create_table(
        'lesson_test_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_id', sa.Integer(), nullable=False),
        sa.Column('patient_token', sa.String(length=64), nullable=False),
        sa.Column('score', sa.Numeric(), nullable=False, server_default='0'),
        sa.Column('max_score', sa.Numeric(), nullable=False, server_default='0'),
        sa.Column('passed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('answers_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['test_id'], ['education.lesson_tests.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='education'
    )
    op.create_index(op.f('ix_education_lesson_test_results_patient_token'), 'lesson_test_results', ['patient_token'], schema='education')
    op.create_index(op.f('ix_education_lesson_test_results_test_id'), 'lesson_test_results', ['test_id'], schema='education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_test_results', schema='education')
    op.drop_table('practice_logs', schema='education')
    op.drop_table('lesson_test_questions', schema='education')
    op.drop_table('lesson_progress', schema='education')
    op.drop_table('lesson_tests', schema='education')
    op.drop_table('practices', schema='education')
    op.drop_table('lesson_cards', schema='education')
    op.drop_table('lessons', schema='education')
    op.drop_index(op.f('ix_water_intake_session_id'), table_name='water_intake', schema='vitals')
    op.drop_index(op.f('ix_water_intake_measured_at'), table_name='water_intake', schema='vitals')
    op.drop_table('water_intake', schema='vitals')
    op.drop_index(op.f('ix_weight_measurements_session_id'), table_name='weight_measurements', schema='vitals')
    op.drop_index(op.f('ix_weight_measurements_measured_at'), table_name='weight_measurements', schema='vitals')
    op.drop_table('weight_measurements', schema='vitals')
    op.drop_index(op.f('ix_pulse_measurements_session_id'), table_name='pulse_measurements', schema='vitals')
    op.drop_index(op.f('ix_pulse_measurements_measured_at'), table_name='pulse_measurements', schema='vitals')
    op.drop_table('pulse_measurements', schema='vitals')
    op.drop_index(op.f('ix_bp_measurements_session_id'), table_name='bp_measurements', schema='vitals')
    op.drop_index(op.f('ix_bp_measurements_measured_at'), table_name='bp_measurements', schema='vitals')
    op.drop_table('bp_measurements', schema='vitals')
    op.drop_index(op.f('ix_scale_results_user_id'), table_name='scale_results', schema='scales')
    op.drop_index(op.f('ix_scale_results_scale_code'), table_name='scale_results', schema='scales')
    op.drop_index(op.f('ix_scale_results_measured_at'), table_name='scale_results', schema='scales')
    op.drop_table('scale_results', schema='scales')
    op.drop_table('sessions', schema='users')
    op.drop_index(op.f('ix_users_researchers_username'), table_name='researchers', schema='users')
    op.drop_table('researchers', schema='users')
    op.drop_index(op.f('ix_users_users_telegram_id'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_patient_token'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_patient_number'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
