"""initial_schema

Revision ID: ebc47ad5a531
Revises: 
Create Date: 2026-02-08 21:00:53.274061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebc47ad5a531'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL OR researcher_id IS NOT NULL'),
    sa.ForeignKeyConstraint(['researcher_id'], ['users.researchers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token'),
    schema='users'
    )
    op.drop_index(op.f('lesson_test_results_quiz_token_idx'), table_name='lesson_test_results', schema='education')
    op.drop_index(op.f('lesson_test_results_token_idx'), table_name='lesson_test_results', schema='education')
    op.drop_table('lesson_test_results', schema='education')
    op.drop_table('alembic_version')
    op.drop_index(op.f('lesson_progress_lesson_idx'), table_name='lesson_progress', schema='education')
    op.drop_index(op.f('lesson_progress_patient_idx'), table_name='lesson_progress', schema='education')
    op.drop_index(op.f('lesson_progress_patient_lesson_uidx'), table_name='lesson_progress', schema='education')
    op.drop_table('lesson_progress', schema='education')
    op.drop_table('responses', schema='scales')
    op.drop_table('drafts', schema='scales')
    op.drop_index(op.f('idx_practice_logs_practice_id'), table_name='practice_logs', schema='education')
    op.drop_index(op.f('idx_practice_logs_user_id'), table_name='practice_logs', schema='education')
    op.drop_table('practice_logs', schema='education')
    op.drop_index(op.f('idx_lesson_cards_lesson_id'), table_name='lesson_cards', schema='education')
    op.drop_table('lesson_cards', schema='education')
    op.drop_index(op.f('lesson_tests_code_uidx'), table_name='lesson_tests', schema='education')
    op.drop_index(op.f('lesson_tests_lesson_idx'), table_name='lesson_tests', schema='education')
    op.drop_table('lesson_tests', schema='education')
    op.drop_index(op.f('idx_practices_lesson_id'), table_name='practices', schema='education')
    op.drop_table('practices', schema='education')
    op.drop_index(op.f('lesson_test_questions_order_uidx'), table_name='lesson_test_questions', schema='education')
    op.drop_index(op.f('lesson_test_questions_test_idx'), table_name='lesson_test_questions', schema='education')
    op.drop_table('lesson_test_questions', schema='education')
    op.drop_table('lessons', schema='education')
    op.drop_index(op.f('ix_researchers_username'), table_name='researchers', schema='users')
    op.create_index(op.f('ix_users_researchers_username'), 'researchers', ['username'], unique=True, schema='users')
    op.drop_index(op.f('ix_users_patient_number'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_patient_token'), table_name='users', schema='users')
    op.drop_constraint(op.f('users_patient_number_key'), 'users', schema='users', type_='unique')
    op.create_index(op.f('ix_users_users_patient_number'), 'users', ['patient_number'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_patient_token'), 'users', ['patient_token'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_patient_token'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_patient_number'), table_name='users', schema='users')
    op.create_unique_constraint(op.f('users_patient_number_key'), 'users', ['patient_number'], schema='users')
    op.create_index(op.f('ix_users_patient_token'), 'users', ['patient_token'], unique=True, schema='users')
    op.create_index(op.f('ix_users_patient_number'), 'users', ['patient_number'], unique=True, schema='users')
    op.drop_index(op.f('ix_users_researchers_username'), table_name='researchers', schema='users')
    op.create_index(op.f('ix_researchers_username'), 'researchers', ['username'], unique=True, schema='users')
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('education.lessons_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey'),
    sa.UniqueConstraint('code', name='lessons_code_key'),
    schema='education',
    postgresql_ignore_search_path=False
    )
    op.create_table('lesson_test_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_2', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_3', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_4', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_option', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['education.lesson_tests.id'], name=op.f('lesson_test_questions_test_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_test_questions_pkey')),
    schema='education'
    )
    op.create_index(op.f('lesson_test_questions_test_idx'), 'lesson_test_questions', ['test_id'], unique=False, schema='education')
    op.create_index(op.f('lesson_test_questions_order_uidx'), 'lesson_test_questions', ['test_id', 'order_index'], unique=True, schema='education')
    op.create_table('practices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('education.practices_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description_md', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], name='practices_lesson_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='practices_pkey'),
    schema='education',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_practices_lesson_id'), 'practices', ['lesson_id'], unique=False, schema='education')
    op.create_table('lesson_tests',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('education.lesson_tests_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], name='lesson_tests_lesson_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lesson_tests_pkey'),
    schema='education',
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('lesson_tests_lesson_idx'), 'lesson_tests', ['lesson_id'], unique=False, schema='education')
    op.create_index(op.f('lesson_tests_code_uidx'), 'lesson_tests', ['code'], unique=True, schema='education')
    op.create_table('lesson_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('card_type', sa.VARCHAR(length=30), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=True),
    sa.Column('content_md', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], name=op.f('lesson_cards_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_cards_pkey')),
    schema='education'
    )
    op.create_index(op.f('idx_lesson_cards_lesson_id'), 'lesson_cards', ['lesson_id'], unique=False, schema='education')
    op.create_table('practice_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('practice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('effect_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['education.practices.id'], name=op.f('practice_logs_practice_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('practice_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('practice_logs_pkey')),
    schema='education'
    )
    op.create_index(op.f('idx_practice_logs_user_id'), 'practice_logs', ['user_id'], unique=False, schema='education')
    op.create_index(op.f('idx_practice_logs_practice_id'), 'practice_logs', ['practice_id'], unique=False, schema='education')
    op.create_table('drafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('drafts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('drafts_pkey')),
    schema='scales'
    )
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scale_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('raw_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interpretation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], name=op.f('responses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('responses_pkey')),
    schema='scales'
    )
    op.create_table('lesson_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_card_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['education.lessons.id'], name=op.f('lesson_progress_lesson_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_progress_pkey')),
    schema='education'
    )
    op.create_index(op.f('lesson_progress_patient_lesson_uidx'), 'lesson_progress', ['patient_token', 'lesson_id'], unique=True, schema='education')
    op.create_index(op.f('lesson_progress_patient_idx'), 'lesson_progress', ['patient_token'], unique=False, schema='education')
    op.create_index(op.f('lesson_progress_lesson_idx'), 'lesson_progress', ['lesson_id'], unique=False, schema='education')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('lesson_test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('score', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_score', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['education.lesson_tests.id'], name=op.f('lesson_test_results_test_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_test_results_pkey')),
    schema='education'
    )
    op.create_index(op.f('lesson_test_results_token_idx'), 'lesson_test_results', ['patient_token'], unique=False, schema='education')
    op.create_index(op.f('lesson_test_results_quiz_token_idx'), 'lesson_test_results', ['test_id', 'patient_token', sa.literal_column('created_at DESC')], unique=False, schema='education')
    op.drop_table('sessions', schema='users')
    # ### end Alembic commands ###
